integration:
  vk:
    api-url: https://api.vk.com
    api-token:
    api-version: 5.131
    poll-interval: 3000
  telegram:
    api-url: https://api.telegram.org
    bot-token:
telegram:
  bot:
    name: Voicemaster
